### ISSUE TITLE
Left wall collision animation frame

### ISSUE THREAD

**Issue by NickCulbertson** [NesHacker/PlatformerMovement#1]
The player sprite shows the slide animation frame while walking into the left wall.

P.S. Amazing work with the YouTube series! It's so cool seeing how all of this stuff works.

**Comment by rsandor** [comment]
Ah! I think I know why this is happening. Let me take a look a bit later and I'll see if I can get it fixed (I'm working in the repo right now as I do gameplay capture for the upcoming video). Thanks so much!
